kind: ConfigMap # 对象类型
apiVersion: v1 # api 版本
metadata: # 元数据
  name: h5sdk # 对象名称
  namespace: fronted
data: # key-value 数据集合
  nginx.conf: | # 将 nginx config 配置写入 ConfigMap 中，经典的 php-fpm 代理设置，这里就不再多说了
    events {
    }
    http {
      include       mime.types;
      default_type  application/octet-stream;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Real-Port $remote_port;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      log_format  main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

      sendfile           on;
      gzip               on;
      tcp_nopush         on;
      tcp_nodelay        on;
      server_tokens     off;
      keepalive_timeout  0;

      client_body_timeout          10;
      client_header_timeout        10;

      client_header_buffer_size    1k;
      large_client_header_buffers  4  4k;
      output_buffers               1  32k;
      client_max_body_size         64m;
      client_body_buffer_size      256k;
      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html/h5game.sentsss.com;
        #index index.php;
        server_name _;
        #location ~ \.php {
        #    fastcgi_pass  127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #    include fastcgi_params;
        #    fastcgi_split_path_info ^(.+\.php)(.*)$;
        #    fastcgi_param PATH_INFO $fastcgi_path_info;
        #}
        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$ {
            expires 30d;
        }

        location ~ .*\.(js|css)?$ {
            expires 12h;
        }

        location / {
            set_real_ip_from 0.0.0.0/0;
            real_ip_header  X-Forwarded-For;
            real_ip_recursive   on;
            index  index.html index.htm index.php;
            if (!-e $request_filename) {
                rewrite  ^(.*)$  /index.php?s=$1  last;
                break;
            }
        }
        access_log  /var/log/nginx/access.log main;
        error_log   /var/log/nginx/error.log error;
        #location ~ \.php$ {
        #  include fastcgi_params;
        #  fastcgi_param REQUEST_METHOD $request_method;
        #  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #  fastcgi_pass 127.0.0.1:9000;
        }
      }
