kind: Ingress # 对象类型
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: h5sdk
  namespace: fronted
spec:
  rules:
    - host: h5game.sentsss.com
      http:
        paths:
        - path: /
          backend:
            serviceName: h5sdk # 流量转发到名为 php-fpm-nginx 的 Server 是那个
            servicePort: 80 # 与 Service 的 port 一致
