apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-logs-filebeat-config
  namespace: kube-system

data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/log/messages
        fields:
          index: "linux-messages"
        #multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
        #multiline.negate: true
        #multiline.match: after 
      - type: log
        enabled: true
        paths:
          - /opt/log/nginx/*/access.log
        fields:
          index: "nginx-access"
        #multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
        #multiline.negate: true
      - type: log
        enabled: true
        paths:
          - /var/log/containers/*.log
        fields:
          index: "containers"
    filebeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: true

    setup.template.settings:
      index.number_of_shards: 1
    setup.kibana:
      hosts: "kibana.kube-system:5601"
    output.elasticsearch:
      hosts: ['elasticsearch.kube-system:9200']
      indices:
        - index: "log_linux_messages-%{+yyyy.MM.dd}"
          pipeline: "log_linux_messages"
          when.contains:
            fields.index: "linux-messages"
        - index: "log_nginx_access-%{+yyyy.MM.dd}"
          pipeline: "log_nginx_access"
          when.contains:
            fields.index: "nginx-access"
        - index: "containers-%{+yyyy.MM.dd}"
          pipeline: "containers"
          when.contains:
            fields.index: "containers"
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-logs
  namespace: kube-system
spec:
  selector:
    matchLabels:
      project: k8s
      app: filebeat
  template:
    metadata:
      labels:
        project: k8s
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: elastic/filebeat:7.3.1
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: filebeat-config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
        - name: k8s-logs
          mountPath: /var/log/messages
        - name: k8s-nginx
          mountPath: /opt/log
      volumes:
      - name: k8s-logs
        hostPath:
          path: /var/log/messages
      - name: k8s-nginx
        hostPath:
          path: /opt/log
      - name: filebeat-config
        configMap:
          name: k8s-logs-filebeat-config
